### ISSUE TITLE
how do i get 100+ tokens in 5 mins from facebook cookies

### ISSUE THREAD

**Issue by Nick8fr32** [pulviscriptor/agario-client#125]
how do i get 100+ tokens in 5 mins 
from facebook cookies

**Comment by d-bots-client** [comment]
@Nick8fr32 do you have mouse control ?

**Comment by Nick8fr32** [comment]
only on spectate

**Comment by hassanila97** [comment]
Easy, you need to have all cookies in an array and if you wanna use NodeJS you gotta use simultaneous express connections to Fb trough proxies (otherwise you will most likely get blocked by FB) and save all responses to a new array and then you can retrieve them easily :)   This would take you 10 secs instead of manual 1hr

**Comment by Nick8fr32** [comment]
@hassanila97 can u help me with that?

**Comment by hassanila97** [comment]
@Nick8fr32 Im currently busy with other stuff...  maybe later I will post an example code here.... if noone helps before.

**Comment by Nick8fr32** [comment]
okay thx @hassanila97

**Comment by Nick8fr32** [comment]
@hassanila97 fb from clan members
