### ISSUE TITLE
Client crashes after a few seconds

### ISSUE THREAD

**Issue by testacc123da** [pulviscriptor/agario-client#26]
Agar.io changed some server things and the bots are not longer working correctly and the script crashes (I think because of Packet from agar.io). I tried a few things but nothing helped :(

Error-Log: http://puu.sh/l2xKN/329a6ad5b3.png

Please fix it!! :*

**Comment by henopied** [comment]
Confirmed!

**Comment by pulviscriptor** [comment]
Uhm, testing `examples/basic.js` for over 30 minutes and can't reproduce crash.
Can you please set `client.debug = 5;` and do like `node myproject.js > debug.log` so i can see packets.
Also lets see:
- `cd node_modules/agario-client` and then `npm list ws`. Show what version you have
- What region you use?
- What server type you use?

**Comment by pulviscriptor** [comment]
I found the problem. In official client's code there is some changes to nicknames. I need some time to investigate if there is something else changed in packet ID 16 and fix it.

**Comment by pulviscriptor** [comment]
Please clone repo and confirm that problem is solved.
Also there is two new variables of balls
https://github.com/pulviscriptor/agario-client/commit/8ef4680864d7674547319e4b0ffc889f9b294dc6
If somebody have free time to investigate what they are, please report them here.
I more interested in first, second is premium skins/colors.

**Comment by pulviscriptor** [comment]
Tested fix for 5 hours running on 3 servers, seems stable.
New variables/props will be added later.
You can run `npm update`
