### ISSUE TITLE
Create a feeder bot

### ISSUE THREAD

**Issue by AmazingGamerBoy** [pulviscriptor/agario-client#29]
Hi guys, wondering if anyone here could help me with something like the link below. Is there anyway to modify pulv's client script to do this. Please contact me if you can help! Thank you!
https://www.youtube.com/watch?v=oy0R6wVFLeY

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
My GitHub Account: AmazingGamerBoy

**Comment by pulviscriptor** [comment]
AmazingGamerBoy, try ask there https://www.reddit.com/r/Agar/ 
There must be already existing bots.

**Comment by pulviscriptor** [comment]
I want to add.
I receive lots of mails with requests like that. I am not interested in doing little bots like that.
But i am interested in developing huge service with thousands of bots and multiple servers, so if you have bag of money and want service like "raga", you can contact me.

**Comment by DeepSnowNeeL** [comment]
Hey ! Thanks to you we created ours ! :)
But we had to move from node.js to java since node.js can't really
multi-thread. (it's more like multi-script and they share data so it was a
mess).
FYI, you can't go over 200/250 bots with node JS :)

Good luck and keep up the good work :)

Le mar. 17 nov. 2015 à 11:50, pulviscriptor <notifications@github.com> a
écrit :

**Comment by l0oky** [comment]
@DeepSnowNeeL That's an interesting note. Is that true? I know that you can make It quite efficient even without clustering node.js processes.

**Comment by DeepSnowNeeL** [comment]
Well from my experience yes, but i'm relatively new to node.js so I don't
know all the things that would speed it up.

Le mar. 17 nov. 2015 à 15:55, Muhamed Krlic <notifications@github.com> a
écrit :

**Comment by nguyenvanduocit** [comment]
if you have money, everything is possible. I have a bot can eat the food and ran towards the main cell and dodge the bigger cell. But agar limit 5 per IP client. So you can not run 150 client per ip.

**Comment by pulviscriptor** [comment]
AmazingGamerBoy, I am closing this issue since it is not an issue, but feel free to comment if you have some questions.

nguyenvanduocit,
28.10.2015 support of agents was added, now is possible to use proxy/SOCKS for connections.
You can check docs in this commit https://github.com/pulviscriptor/agario-client/commit/5db61159cc92b4011e3d8d660183d6de13ba98a7
You can check SOCKS usage example in https://github.com/pulviscriptor/agario-client/blob/master/examples/socks.js
