### ISSUE TITLE
When I try to spawn more than 30 bots on party

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#47]
buffer.js:788
    throw RangeError('Trying to write outside buffer length');
    ^
RangeError: Trying to write outside buffer length
    at RangeError (<anonymous>)
    at checkInt (buffer.js:788:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at Object.Client.onConnect (/opt/razor.secureobscure.com/bots/agario-client.js:93:17)
    at WebSocket.onOpen (/opt/razor.secureobscure.com/node_modules/ws/lib/WebSocket.js:432:14)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.establishConnection (/opt/razor.secureobscure.com/node_modules/ws/lib/WebSocket.js:862:8)
    at ClientRequest.upgrade (/opt/razor.secureobscure.com/node_modules/ws/lib/WebSocket.js:753:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:106:17)
    at Socket.socketOnData (http.js:1612:11)

Is it because I updated ws?

**Comment by pulviscriptor** [comment]
"Trying to <b>write</b> outside buffer length"? This is something new.
By looking at your `agario-client.js` location in `bots/agario-client.js` is wrong. It must be in `node_modules` folder so i assume you modified original code of lib. This is very wrong.
Open your `agario-client.js` and show me `onConnect: function() { ...` block. 
Mine looks like this http://pastebin.com/raw/EHPBjtEa
Your should be exact same. If your are modified, you using lib wrong way.
But just to be sure, show me that block of code.

**Comment by DeepSnowNeeL** [comment]
Hi, I'm running agarbot.ovh. We used a modified version of your code for
our first version back in november. When we had around 250 bots, packets
starts to "de-sync", so you might encounter a lot of buffer overflow /
buffer underflow / incorrect packet id because of the datastream index
shifting/skiping few bytes.
We fixed it by re-developping everything in java. But it is mainly because
of the way node.js and your OS / network communicate. I don't think you
can't find another solution than ignore errors (try catch them and let it
go). Bots can still run if they miss some update (packet 16), but you might
not detect the bot death so take care. I would personally disconnect the
bot and reconnect a new one on error.
If needed I can check our old logs, I would be able to give a few more
examples with stacktraces.

Have fun !

Le ven. 8 janv. 2016 à 06:55, pulviscriptor <notifications@github.com> a
écrit :

**Comment by pulviscriptor** [comment]
@DeepSnowNeeL This is what i did in issue 46 https://github.com/pulviscriptor/agario-client/issues/46
There is now `client.on.packetError` event.
But this issue is related to sending packets. I'm almost sure that @DaAwesomeRazor broke his client by modifying something in `onConnect` block. Original block looks like this  http://pastebin.com/raw/EHPBjtEa and there should not be any errors.

**Comment by DaAwesomeRazor** [comment]
I just edited a few things in agarioclient.js so I ccan get more than 5 bots. Socks5 wasnt working

**Comment by DaAwesomeRazor** [comment]
Oh I did modify the onConnect though. I added localAddress

**Comment by pulviscriptor** [comment]
@DaAwesomeRazor is there bug in client's code, or you solved the problem?

**Comment by davidmann4** [comment]
@DaAwesomeRazor what exactly did you changed?

**Comment by DaAwesomeRazor** [comment]
I havent solved the problem but, im trying to fix it right now

**Comment by henopied** [comment]
Can confirm, no modifications to the agar client.

**Comment by pulviscriptor** [comment]
@henopied
You can confirm the crash?
@DaAwesomeRazor
Show me your `onConnect: function() { ...` block please.

**Comment by davidmann4** [comment]
@DaAwesomeRazor 
I guess the 5 connections limit is a server side limitation...

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor 
connect: function(server, key, localAddress) {
        var headers = {
            'Origin': 'http://agar.io'
        };

        this.ws            = new WebSocket(server, null, {headers: headers, agent: this.agent, localAddress: localAddress});
        this.ws.binaryType = "arraybuffer";
        this.ws.onopen     = this.onConnect.bind(this);
        this.ws.onmessage  = this.onMessage.bind(this);
        this.ws.onclose    = this.onDisconnect.bind(this);
        this.ws.onerror    = this.onError.bind(this);
        this.server        = server;
        this.key           = key;

        if(this.debug >= 1) {
            if(!key) this.log('[warning] You did not specified "key" for Client.connect(server, key)\n' +
                '          If server will not accept you, this may be the problem');
            this.log('connecting...');
        }

        this.emit('connecting');
    },

**Comment by pulviscriptor** [comment]
@DaAwesomeRazor 
You got `connect` block, but i need `onConnect`
https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L73

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor  I dont think I changed that

**Comment by pulviscriptor** [comment]
@DaAwesomeRazor
Do you still have crash `Trying to write outside buffer length` in `onConnect`? And how often you see it?
And if you do have it, show me `onConnect` block please.

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor  I got it to work! I just recoded my client and updated the Agario Client it wasnt up to date.
