### ISSUE TITLE
My bots slowly disconnect after connecting to a server

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#69]
http://pastebin.com/jU5zygAy
There are the logs
is this because of socks proxies being slow?

**Comment by pulviscriptor** [comment]
If you use auth token, test your code without token.
If you use more than 1 bot per sock, test your code with 1 bot per sock.

**Comment by DaAwesomeRazor** [comment]
kk

**Comment by issy123** [comment]
Max allowed bots on server with same agario-client ip: 3
Max allowed bots with same facebook account per agario-server ip: 1

**Comment by DaAwesomeRazor** [comment]
I know that

**Comment by DaAwesomeRazor** [comment]
Well i just figured it out before I read your post.. It still gives the errors

**Comment by issy123** [comment]
You can add me on skype: ismail.metaich

**Comment by Sonicmaster13** [comment]
Nah, we have our code fine its just that the bots slowly start to get kicked from the server. We have no Facebook attached due to agario's Facebook update breaking Facebook bots, and are not trying to use more then 3 per party server or 1 per other modes. They just start to stop moving and get disconnected.
