### ISSUE TITLE
movement features

### ISSUE THREAD

**Issue by issy123** [pulviscriptor/agario-client#72]
It would be nice to ad an third optional parameter to the `moveTo` command. Speed.
`moveTo(x,y,speed)`

This extra level of control is both usefull in spectatemode and in play mode.

It would be also nice to add an `stop()` function which will stop the bot immediatly. If the bot has multiple balls it will find its center of 'gravity' to stop

**Comment by pulviscriptor** [comment]
As you can [see](https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L573) `moveTo()` is very primitive. It just makes and sends packet to server.
And there is no `speed` thing in protocol, there is only `x` and `y`.
Speed is calculated by server and depends on distance from your ball to `moveTo()` coordinates.
There also no such thing as `stop` command in protocol. Instead sending `moveTo()` with your current coordinates should work fine.
But i don't think i want to implement it in lib because it will be too complicated for multiple balls (you need to calculate one center for all balls that you have).
