### ISSUE TITLE
Reduce CPU usage of agario-client

### ISSUE THREAD

**Issue by Ogarunite** [pulviscriptor/agario-client#85]
Hi, i've looked a bit into agario-client and it seems it has some functions which can be removed/ignored to reduce CPU/RAM. Some of these i've seen are the packet '50' (teams) and '16' (world) which registers things such as other 'balls', pellets, and viruses around. How can I remove the ability of agario-client to register other things than itself? Is it possible to jump out of the code for '16' if the ball_registered is not "ours"?

**Comment by pulviscriptor** [comment]
Client don't have such "low level" api so i can only recommend modify sourecode by removing code that you don't need to reduce cpu/ram.

**Comment by Ogarunite** [comment]
I tried removing the whole '16' but then several problems appear, and the bot doesn't know if it dies, it should respawn again.

for (var i = 0; i < client.my_balls.length; i++) {
ball_skip = client.my_balls[i];
if (ball_skip != ball_id) {
break;
}
Can you help me change this code so that the bot will jump out from checking other 'balls' around it?

**Comment by issy123** [comment]
I have read your issue about CPU/RAM usage. I am facing the same problem. I will soon do a pull request that will improve also on the performance.

**Comment by DanielLewis97NL** [comment]
@Ogarunite  

ball_id = packet.readUInt32LE();
if(ball_id == 0 || !client.balls[ball_id].mine) break;

**Comment by issy123** [comment]
What I thought would fix the CPU usage problem is to only process those packages that has event listeners bind to it.

For example if the event LeaderboardUpdate has no listeners, dont process the leaderboard update package.

But as I found out most of the events are required to be processed even if there are no listeners to it.
It handles respawn, connection and detect if you are dead etc. So not so much performance gain :(

But if your bots are only concerned about itself you could strip agario-client to only parse those data that has something to do about the bot and not about other players.
You wont receive leaderboard update, who ate you and big players around you but you will notice an performance gain since those data about other cells are not processed.

**Comment by Ogarunite** [comment]
Issy, could you help me strip that data?

**Comment by issy123** [comment]
Yes. But i don't know if its worth it since the last time they said they are patching bots.

If bots still work tomorrow i will be able to help

**Comment by Ogarunite** [comment]
Thanks. My gmail is ogarunite@gmail.com
