### ISSUE TITLE
Coordinates scrambled

### ISSUE THREAD

**Issue by issy123** [pulviscriptor/agario-client#89]
Bots dont follow the direction my client has.

So when I am at postion xxxx:xxxx, i send I am at xxxx:xxxx but the bot goes to yyyy:yyyy.

Maybe its scrambled or the cords packet is changed

**Comment by DaAwesomeRazor** [comment]
@issy123 agario broke it. The map dimensions are now your view base

**Comment by pulviscriptor** [comment]
I am busy for few days so if somebody could look into the problem that would be nice.

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor I think we figured out how to get it to work in spctate moe if that helps

**Comment by Sonicmaster13** [comment]
We are working on it.

**Comment by pulviscriptor** [comment]
I have looked at what they made. Now all clients have random map size coordinates. 
If you have single bot, you fine. 
If you have multiple bots that needs to cooperate with each other, you have a problem. Now there is no "correct" coordinates, they all different for all clients.
Unfortunately there is nothing i can do (i just can't think of any fix that will help).
Also i recommend to delete all balls from `bot.balls` before you re-spawn, because old balls will have invalid coordinates.
Will not add this to client because agar can change this any time.

**Comment by Nick8fr32** [comment]
@pulviscriptor i think i have a way we can fix this?

**Comment by pulviscriptor** [comment]
@Nick8fr32
You have way to fix it or you asking if i do? I do not know how i can fix that in lib.
I think its now challenge for bot makers to make coordinates management stuff.

**Comment by Nick8fr32** [comment]
i think i got a way to fix it but i will take some time to make and i cant make it on my own

**Comment by pulviscriptor** [comment]
Can you explain what your solution is?

**Comment by Nick8fr32** [comment]
not here maybe miniclip watch this

**Comment by issy123** [comment]
Yea we all could help. If you got the solution we got the code:D

**Comment by Nick8fr32** [comment]
that will be nice because i suck to code =P

**Comment by issy123** [comment]
So how can you tell us? mail me: ztcnxovu@grandmamail.com
its a temporary mail.
